
const Terms = () => {
    return (
        <main className="w-full bg-primaryLight dark:bg-primaryDark mx-auto">
            <div className="auto-padding py-14">
            
                    <p className="py-5 title-h3 text-center">TERMS AND CONDITIONS</p>
                    <p className="text !text-[16px] mb-2">This document governs the Business relationships between <strong>FastAdvisors OU</strong> (“<strong>Siquro</strong>”) and you as a “<strong>Merchant</strong>”. Access to and use of <strong>Siquro</strong> services by the <strong>Merchant</strong> is subject to compliance with all terms and conditions set forth hereinafter together with payment processing services contract and annexes if any. Please read carefully before signing and accepting the terms and conditions of this Agreement.</p>
                    <p className="text !text-[16px] mb-2">By accepting these General Terms and Conditions (hereinafter – “Agreement”), you declare that you are the authorized representative of the <strong>Merchant</strong> and that with your signature (or acceptance if online), the <strong>Merchant</strong> acknowledges that the Terms and Conditions were read and understood (or have sought legal advice on them) and agrees to be bound by them. Acceptance of these Terms and Conditions will also be considered any use of one or more of the services described below. If the <strong>Merchant</strong> does not agree with these Terms and Conditions, then the <strong>Merchant</strong> should not use any of the services, nor sign this Agreement (or decline if online). By using the Services, you authorize <strong>Siquro </strong>to act as your agent so <strong>Siquro</strong> may receive, hold, and disburse funds on your behalf and to take any and all actions that it thinks are necessary to provide the Services and to comply with all applicable laws.</p>
                    <ol className="py-5 title-h4">
                        <li>INTRODUCTION</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">1.1. This Agreement along with the Payment Processing Services Contract and other applicable policies the <strong>Merchant</strong> has agreed for by signing them or agreed online form the relationship between the <strong>Merchant</strong> (“You”, “Your”) and its agents and/or authorized representatives, and <strong>Siquro</strong> (hereinafter – the “Company”). Making use of any of the services of <strong>Siquro</strong> constitutes acceptance of the Terms and Conditions, and for <strong>Siquro</strong> to establish a <strong>Merchant</strong> account for the <strong>Merchant</strong>. The <strong>Merchant</strong> further agrees that the Agreement (and any update thereof) will also cover <strong>Merchant</strong>’s use of the <strong>Merchant</strong> account to add services to <strong>Merchant</strong>’s service plan, to modify or to cancel <strong>Merchant</strong>’s service plan. Even in the absence of any notification to <strong>Siquro</strong>, the Agreement is also applicable to any other person (legal or natural) <strong>Merchant</strong> grants permission to use its <strong>Merchant</strong> account.</p>
                    <p className="text !text-[16px] mb-2">1.2. <strong>Merchant</strong> confirms that the designated person (or persons) as its authorized representative(s) has/have been granted full authority to act on its behalf in relation to the <strong>Siquro</strong> Service/s (and as this may be modified from time to time), and that any such actions taken by him/her/them including but not limited to purchase of additional services, modification of the service plan, termination, or transfer of the service plan, would be considered binding and final.</p>
                    <p className="text !text-[16px] mb-2">1.3. All Paragraphs described below apply to any (and all) of the services that <strong>Merchant</strong> purchases/uses under this Agreement.</p>
                    <ol className="py-5 title-h4">
                        <li> DEFINITIONS AND INTERPRETATIONS</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">In the present Terms and Conditions the following terms shall, unless the context otherwise requires, have the following meanings and may be used in the singular or plural as appropriate:</p>
                    <p className="text !text-[16px] mb-2">2.1. <strong>Acquirer:</strong> An entity contracted by <strong>Siquro</strong> to submit Sales Drafts and transaction information to the Card Organizations on behalf of <strong>Siquro</strong> and to receive and pay to <strong>Siquro</strong> settlement funding for such sales transactions;</p>
                    <p className="text !text-[16px] mb-2">2.2. <strong>Affiliate:</strong> An “Affiliate” of a party is a Person that, directly or indirectly: (i) owns or controls such party; or (ii) is under common ownership or control with such party;</p>
                    <p className="text !text-[16px] mb-2">2.3. <strong>Applicable Law:</strong> All national and international statutes, ordinances, laws, regulations, and executive, administrative, and judicial orders applicable to the Agreement, the transactions, or other matters contemplated under the Agreement, and all amendments thereto; and with respect to Bank and/or Acquirer, also guidance by its financial institution regulators;</p>
                    <p className="text !text-[16px] mb-2">2.4. <strong>Authorization:</strong> A confirmation and approval reception of the Transaction from the Card Issuing Bank and suited Card Organization;</p>
                    <p className="text !text-[16px] mb-2">2.5. <strong>Bank:</strong> A financial institution that is a member of the Card Organizations and provides Card Organization sponsorship for Card transactions submitted by <strong>Siquro</strong> for processing hereunder, also referred to as “Member”;</p>
                    <p className="text !text-[16px] mb-2">2.6. <strong>Businesses day:</strong> A day, other than a Saturday or a Sunday, or official public or <strong>Siquro</strong>/Acquirer/Bank holiday;</p>
                    <p className="text !text-[16px] mb-2">2.7. <strong>Card:</strong> Either Credit Card or Debit Card;</p>
                    <p className="text !text-[16px] mb-2">2.8. <strong>Cardholder:</strong> The Person whose name is embossed on a Card (or Debit Card, as applicable) and any legally authorized user of such Card;</p>
                    <p className="text !text-[16px] mb-2">2.9. <strong>Card Organization:</strong> Any entity formed to administer and promote Cards, including without limitation Mastercard Worldwide (“Mastercard”), Visa Europe Ltd. (“Visa”), and any applicable debit networks;</p>
                    <p className="text !text-[16px] mb-2">2.10. <strong>Card Organization Rules:</strong> The rules, regulations, releases, interpretations, and other requirements (whether contractual or otherwise) imposed or adopted by any Card Organization and related authorities, including without limitation, those of the PCI Security Standards Council, LLC;</p>
                    <p className="text !text-[16px] mb-2">2.11. <strong>Chargeback:</strong> A Card transaction (or disputed portion) that is returned to Acquirer and/or Bank by the Issuer;</p>
                    <p className="text !text-[16px] mb-2">2.12. <strong>Compliance:</strong> Abidance of all applicable laws, rules and regulations, and the relevant rules, regulations and policies of the <strong>Card Organizations;</strong></p>
                    <p className="text !text-[16px] mb-2">2.13. <strong>Credit:</strong> A refund or price adjustment given for a previous purchase transaction.</p>
                    <p className="text !text-[16px] mb-2">2.14. <strong>Credit Card:</strong> A device bearing a valid Card Organization Mark and authorizing the Cardholder to buy goods or services on credit;</p>
                    <p className="text !text-[16px] mb-2">2.15. <strong>Debit Card:</strong> See either PIN Debit Card or Non-PIN Debit Card;</p>
                    <p className="text !text-[16px] mb-2">2.16. <strong>Issuer:</strong> The financial institution or Card Organization which has issued a Card to a Person.</p>
                    <p className="text !text-[16px] mb-2">2.17. <strong>Fraudulent Transaction: </strong>An unauthorized Card transaction, when third person obtains Cardholder’s credit card details and uses them over the phone or on the Internet to make purchases in <strong>Merchant</strong>’s name;</p>
                    <p className="text !text-[16px] mb-2">2.18. <strong>Holdback (Holdback) or Rolling Reserve:</strong> An amount established and funded pursuant to terms set forth in this Agreement and Payment Processing Services Contract to serve as security for amounts owed by <strong>Merchant</strong> to <strong>Siquro</strong> under this Agreement;</p>
                    <p className="text !text-[16px] mb-2">2.19. <strong>Marks:</strong> Names, logos, emblems, brands, service marks, trademarks, trade names, tag lines, or other proprietary designations;</p>
                    <p className="text !text-[16px] mb-2">2.20. <strong>Member:</strong> A financial institution that is a member of the Card Organizations and provides Card Organization sponsorship for Card transactions submitted by <strong>Siquro</strong> for processing hereunder, also referred to as “Bank” and/or “Acquirer”;</p>
                    <p className="text !text-[16px] mb-2">2.21. <strong>Merchant Application Form – </strong>an application completed by the <strong>Merchant </strong>before this Agreement and Payment Processing Services Contract become effective and which contains the information regarding the <strong>Merchant</strong>’s<strong> </strong>nature of provided business, business-operating company/ies, ultimate beneficial owner/s, estimated turnover, etc;</p>
                    <p className="text !text-[16px] mb-2">2.22. <strong>Merchant Category Code (MCC): </strong>A four-digit number assigned to a <strong>Merchant</strong> by the Acquirer/<strong>Siquro</strong>, when the <strong>Merchant</strong> first starts accepting Credit cards as a form of payment;</p>
                    <p className="text !text-[16px] mb-2">2.23. <strong>Merchant Provider:</strong> Any Person engaged to provide services involving or relating to: (i) access to Cardholder data transaction data or information related to either Cardholder data or transaction data; or (ii) PIN encryption, including without limitation, Encryption Service Organizations (ESOs), also referred to as “Third Party Service Provider”;</p>
                    <p className="text !text-[16px] mb-2">2.24. <strong>MID (Merchant Identification number)</strong>: is a unique number assigned to a <strong>Merchant </strong>account to identify it throughout the course of processing activities, generated by the Acquirer/<strong>Siquro</strong>/Bank;</p>
                    <p>2.25. <strong>Non-PIN Debit Card:</strong> A device with a Card Organization Mark that is tied to a Cardholder’s account or a prepaid account and which is processed without the <strong>Siquro</strong> e of a PIN;</p>
                    <p className="text !text-[16px] mb-2">2.26. <strong>Siquro:</strong> An authorized Money Services Business (MSB) entity by the Financial Transactions and Reports Analysis Centre of Canada (FINTRAC) registered by an Acquirer and/or bank to acquire Transactions on behalf of <strong>Merchant</strong>s;</p>
                    <p className="text !text-[16px] mb-2">2.27. <strong>PCI DSS: </strong>The Payment Card Industry Data Security Standard, which is a proprietary information security standard for organizations that handle branded credit cards from the major card schemes including Visa, Mastercard, American Express, Discover, and JCB;</p>
                    <p className="text !text-[16px] mb-2">2.28. <strong>Person:</strong> A third party individual or entity, other than the <strong>Merchant</strong>;</p>
                    <p className="text !text-[16px] mb-2">2.29. <strong>PIN:</strong> A Personal Identification Number entered by the Cardholder to submit a PIN Debit Card transaction;</p>
                    <p>2.30. <strong>PIN Debit Card:</strong> A device bearing the Marks of ATM networks used at a <strong>Merchant</strong> location by means of a Cardholder-entered PIN in the <strong>Merchant</strong> PIN Pad;</p>
                    <p className="text !text-[16px] mb-2">2.31. <strong>Recurring Transaction: </strong>A charge applied to a Cardholder in predetermined intervals for services or goods of an ongoing nature (memberships, subscriptions);</p>
                    <p className="text !text-[16px] mb-2">2.32. <strong>Retrieval Request/Transaction Documentation Request:</strong> A request for documentation related to a Card transaction such as a copy of a Sales Draft or other transaction source documents;</p>
                    <p className="text !text-[16px] mb-2">2.33. <strong>Sales Draft:</strong> Evidence of a purchase, rental or lease of goods or services by a Cardholder from, and other payments to, <strong>Merchant</strong> using a Card, regardless of whether the form of such evidence is in paper or electronic form or otherwise, all of which must conform to Card Organization Rules and Applicable Law;</p>
                    <p className="text !text-[16px] mb-2">2.34. <strong>SDP:</strong> A Site Data Protection Program designed to ensure that <strong>Siquro</strong>, <strong>Merchant</strong>s and third party service providers take adequate measures to protect against account data compromises;</p>
                    <p className="text !text-[16px] mb-2">2.35. <strong>Services:</strong> The authorization, processing, and settlement services provided by <strong>Siquro</strong> to <strong>Merchant</strong> pursuant to the terms and conditions set forth in this Agreement;</p>
                    <p className="text !text-[16px] mb-2">2.36. <strong>Settlement Account:</strong> An account or account(s) at a financial institution designated by <strong>Merchant</strong> as the account to be debited and credited by <strong>Siquro</strong> for Card transactions, fees, Chargebacks, and other amounts due under or in connection with this Agreement and Payment Processing Services Contract;</p>
                    <p className="text !text-[16px] mb-2">2.37. <strong>Third Party Service Provider:</strong> Any Person engaged to provide services involving or relating to (i) access to Cardholder data, transaction data or information related to either Cardholder data or transaction data or (ii) PIN encryption, including without limitation, Encryption Service Organizations (ESOs), also referred to as “Merchant Provider.”</p>
                    <ol className="py-5 title-h4">
                        <li>SCOPE OF THE SERVICES</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">3.1. The Services allow <strong>Merchant</strong> to accept payment card (Visa and/or Mastercard) transactions into its <strong>Merchant</strong> account, which is handled by <strong>Siquro</strong>.</p>
                    <p className="text !text-[16px] mb-2">3.2. <strong>Siquro</strong> is a Money Services Business (MSB) entity, which is entitled to provide payment services and shall not be considered a credit institution.</p>
                    <p className="text !text-[16px] mb-2">3.3. <strong>Siquro</strong> provides to <strong>Merchant</strong> payment services that facilitate <strong>Merchant</strong>’s acceptance of credit and debit card payments as a form of payment for goods, services and/or other facilities provided to Cardholders through the <strong>Merchant</strong>’s website/s. To do so, <strong>Siquro</strong> enters into agreements with other authorized payment services providers and/or banks.</p>
                    <p>3.4. By opening a <strong>Merchant</strong> account with <strong>Siquro</strong>, <strong>Merchant</strong> is required to provide certain accurate and complete information, as well as other documentation required by <strong>Siquro</strong>, which must be approved by <strong>Siquro</strong> prior to using the Services.</p>
                    <p className="text !text-[16px] mb-2">3.5. By entering into this Agreement, <strong>Merchant</strong> provides an authorization for <strong>Siquro</strong> to share provided information with bank or other financial institution <strong>Siquro</strong> has established contractual relationship with.</p>
                    <p className="text !text-[16px] mb-2">3.6. If the request to open a <strong>Merchant</strong> account is approved, <strong>Siquro</strong> is entitled to request additional information from <strong>Merchant</strong> at any time. <strong>Siquro</strong> may also require additional information at any time to keep up to date Merchant’s record and to determine whether <strong>Merchant</strong> continues to meet the requirements for a <strong>Merchant</strong> Account.  Additionally, <strong>Merchant</strong> may be required to enter into additional agreements as required by <strong>Siquro</strong> or the card organizations (Mastercard and Visa).</p>
                    <p className="text !text-[16px] mb-2 text-wrap">3.7. The Services work with Visa and Mastercard Card Organizations’ credit, debit, and prepaid cards.<strong> Siquro</strong> may remove or add Cards or alternative payment methods that it accepts at any time and without prior notice to <strong>Merchant</strong>. The Card Organizations require that <strong>Merchant</strong> complies with all applicable laws, rules, and regulations, which may benamended at any time. <strong>Siquro</strong> may be required to amend this agreement to comply with such amendments on case-by-case basis.</p>
                    <ol className="py-5 title-h4">
                        <li>MERCHANT’S DUTIES AND RESPONSIBILITIES</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">It is the <strong>Merchant</strong>’s sole responsibility to:</p>
                    <p className="text !text-[16px] mb-2">4.1. Frequently check the status of the <strong>Merchant</strong>’s account maintained with <strong>Siquro</strong> and to ensure by reviewing with similar frequency the <strong>Merchant</strong> account’s transaction history in order to ascertain if any unauthorized activity has taken place. When the <strong>Merchant</strong> suspects that unauthorized activity occurred, the suspicion should be promptly communicated to <strong>Siquro</strong>.</p>
                    <p className="text !text-[16px] mb-2">4.2. Develop and maintain (including hosting arrangements of) the <strong>Merchant</strong> website ensuring its accessibility on the internet for the customers. Through the <strong>Merchant</strong>’s website, the <strong>Merchant</strong> should ensure that any placed orders for products and/or services it sells will be properly fulfilled. The <strong>Merchant</strong> must also ensure unobstructed transmission of any transactional information to <strong>Siquro</strong> servers and that the <strong>Merchant</strong>’s system (software and hardware) is not tainting the transmitted information in any way.</p>
                    <p className="text !text-[16px] mb-2">4.3. Ensure that the software used is updated to the latest version and that any required security updates and patches are in place.</p>
                    <p className="text !text-[16px] mb-2">4.4. Ensure that the customer’s registration information requested at the Merchant website as well as the available payment information is always up to date.</p>
                    <p className="text !text-[16px] mb-2">4.5. Ensure that there is at least one active commercial banking relationship with a credit institution. <strong>Siquro</strong> will have no bearing on this relationship and any terms and conditions set out by such a relationship will have no bearing on <strong>Siquro</strong> and will be the sole responsibility of the <strong>Merchant</strong> and the credit institution(s).</p>
                    <p className="text !text-[16px] mb-2">4.6. Ensure that collection, storage and transmission of customer data is performed using security policies that are in line with business best practices and which protect the privacy of <strong>Merchant</strong> data as required by the Personal Information Protection and Electronic Documents Act (“PIPEDA”). For using its service, <strong>Siquro</strong> may review the <strong>Merchant</strong> data handling process and if deemed necessary, request that the <strong>Merchant</strong> undertake to bolster its process, within reasonable commercial limits, to further safeguard the customer data and the overall security of the <strong>Siquro</strong> service.</p>
                    <p className="text !text-[16px] mb-2">4.7. Ensure that any information procured through the use of the <strong>Siquro</strong> service should only be used in conjunction with the service and in such a way that it is not acceptable in accordance with the Agreement and the <strong>Siquro</strong> policies. The <strong>Merchant</strong> should not permit the use of such information by any other third party other than in conjunction with the service.</p>
                    <p className="text !text-[16px] mb-2">4.8. Use the <strong>Siquro</strong> service in accordance with the terms and conditions stipulated in the Agreement, Payment Processing Services Contract, the Policies, and other User Guides and/or Manuals that <strong>Siquro</strong> may publish from time to time.</p>
                    <p className="text !text-[16px] mb-2">4.9. Ensure that the <strong>Merchant</strong> is up to date with any amendments to the terms and conditions of the Agreement and with any changes to the services provided by <strong>Siquro</strong> from time to time.</p>
                    <ol className="py-5 title-h4">
                        <li>SIQURO DUTIES AND RESPONSIBILITIES</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">5.1. <strong>Siquro</strong> agrees (always subject to the terms and conditions of the Agreement) and is responsible to:</p>
                    <p className="text !text-[16px] mb-2">(i) Provide the services for which the <strong>Merchant</strong> subscribes to and pays for;</p>
                    <p className="text !text-[16px] mb-2">(ii) Provide the <strong>Merchant</strong> with (or provide access to through the <strong>Siquro</strong> system) standardized transaction reports as well as accounting reporting tools that the <strong>Merchant</strong> can use in preparation of its accounting records.</p>
                    <p>5.2. <strong>Siquro</strong> has the right and the <strong>Merchant</strong> agrees that it may at any time:</p>
                    <p className="text !text-[16px] mb-2">(i) Amend the terms and conditions of the Agreement including any and all of its Schedules;</p>
                    <p className="text !text-[16px] mb-2">(ii) Change all or part of the services it offers to the <strong>Merchant</strong> under the Agreement.</p>
                    <p className="text !text-[16px] mb-2">5.3. The <strong>Merchant</strong> can choose to terminate the Agreement at any time by notifying <strong>Siquro</strong> in the manner stipulated in the Termination Paragraph of this Agreement, if it objects to the amendments in the terms and conditions and/or the changes in the services provided by <strong>Siquro</strong>. The <strong>Merchant</strong> agrees that upon termination of the Agreement and paid fees will not be refunded and <strong>Siquro</strong> agrees that no additional fees will be charged. For clarification purposes, any fees that are still due to <strong>Siquro</strong> and owed by the <strong>Merchant</strong> will remain due and the <strong>Merchant</strong> should settle them even if the Agreement has been terminated.</p>
                    <p>5.4. Continued use of the services by the <strong>Merchant</strong> will be considered as acceptance of the amendments and/or changes, and the <strong>Merchant</strong> agrees to be bound by them. By continuing to use <strong>Siquro</strong> services after any revision to this Agreement or change in Services, <strong>Merchant</strong> agrees to abide by and be bound by any such revisions or changes.</p>
                    <p className="text !text-[16px] mb-2">5.5. Security of transactions is significant to <strong>Siquro</strong>, which has employed and will sustain adequate security systems to ensure secure transmission of <strong>Merchant</strong>’s Transactions over the internet. The security measures taken consist of encryption and firewall systems as well as publicly known intrusion prevention mechanisms. For encryption <strong>Siquro</strong> will use Secure Socket Layer (SSL) technology which is considered the standard, while for the firewall system it will use a combination of hardware and software that will result in all external traffic terminating at a demilitarized firewalled zone.</p>
                    <p className="text !text-[16px] mb-2">5.6. <strong>Siquro</strong> does not guarantee the security of the Services or Transaction data and will not be responsible in the event of any infiltration of its security systems, provided that <strong>Siquro</strong> has used commercially reasonable efforts to prevent any such infiltration. <strong>Merchant</strong> further acknowledges and agrees that it, and not <strong>Siquro</strong>, is responsible for the security of Transaction data, or information or any other information stored on <strong>Merchant</strong>’s servers, and that <strong>Siquro</strong> is not responsible for any other party’s servers (other than subcontractors of <strong>Siquro</strong> solely to the extent it is liable for its own actions hereunder).</p>
                    <ol className="py-5 title-h4">
                        <li>MERCHANT ACCOUNT</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">6.1. By establishing a <strong>Merchant</strong> Account, <strong>Merchant</strong> confirms that <strong>Merchant</strong>’s business-operating entity and activity are authorized to conduct business by the country in which it operates.</p>
                    <p className="text !text-[16px] mb-2">6.2. The Services may only be used within the countries that allow doing so.</p>
                    <p className="text !text-[16px] mb-2">6.3. <strong>Merchant</strong> provides <strong>Siquro</strong> the authorization to contact and share information about its <strong>Merchant</strong> Account with <strong>Merchant</strong>’s bank or other financial institution. Upon approval of <strong>Merchant</strong> Account and by accepting the terms of this Agreement, <strong>Merchant</strong> provides the authorization <strong>Siquro</strong> to hold, receive, and disburse funds on its behalf. <strong>Merchant</strong> may terminate this authorization by closing its <strong>Merchant</strong> Account.</p>
                    <p className="text !text-[16px] mb-2">6.4. <strong>Merchant</strong> agrees to do the following:</p>
                    <p className="text !text-[16px] mb-2">(i) Comply with all applicable laws and regulations and all requirements of Card Organizations applicable to <strong>Merchant</strong>s;</p>
                    <p className="text !text-[16px] mb-2">(ii) Maintain the security of <strong>Merchant</strong>’s Account as part of its use of the Services.</p>
                    <p className="text !text-[16px] mb-2">(iii) Not accept payments in connection with any illegal activity;</p>
                    <p className="text !text-[16px] mb-2">(iv) Use the Services only for lawful <strong>Merchant</strong> activities as approved by <strong>Siquro</strong> and not in a manner that results in or may result in complaints, disputes, chargebacks, fees, fines, or penalties; and</p>
                    <p className="text !text-[16px] mb-2">(v) Not use the Services to process cash advances.</p>
                    <ol className="py-5 title-h4">
                        <li>UNAUTHORIZED USE OF THE SERVICES</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">7.1. <strong>Merchant</strong> is entitled to use the Services only in compliance with all laws, rules, and regulations applicable to the use of the Services.</p>
                    <p className="text !text-[16px] mb-2">7.2. <strong>Siquro</strong> may choose not to authorize or settle any submitted transaction, if <strong>Siquro</strong> considers the transaction is  in  violation  of  this  Agreement  and Payment Processing Services Contract may  cause  harm  to <strong>Merchant</strong>,  the  <strong>Siquro</strong>  or  its  partners.</p>
                    <p className="text !text-[16px] mb-2">7.3. <strong>Merchant</strong> expressly provides the authorization <strong>Siquro</strong> to share information about <strong>Merchant</strong>, <strong>Merchant</strong>’s Account or its transactions with law enforcement if <strong>Siquro</strong> considers the Services have been used for an illegal, unauthorized or criminal purpose.</p>
                    <ol className="py-5 title-h4">
                        <li>FINANCIAL INFORMATION</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">8.1. The <strong>Merchant</strong> is obliged to provide <strong>Siquro</strong> with financial statements and other related information upon request by <strong>Siquro</strong>.  Such financial statements and other related documents required to be prepared in accordance with generally accepted accounting standards.</p>
                    <p className="text !text-[16px] mb-2">8.2. <strong>Siquro</strong> may also require providing other information concerning <strong>Merchant</strong>’s business activity and its compliance with the terms and provisions of this Agreement as <strong>Siquro</strong> may reasonably request.</p>
                    <ol className="py-5 title-h4">
                        <li>FEES AND PAYMENTS</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">9.1. <strong>Merchant</strong> agrees to pay the applicable fees set forth in this Agreement, as well as in Payment Processing Services Contract.</p>
                    <p className="text !text-[16px] mb-2">9.2. <strong>Siquro</strong> reserves the right to change Fees at any time with reasonable prior notice of such changes to the <strong>Merchant</strong>. <strong>Merchant</strong>’s continuous use of the Services indicates its consent to the change in Fees. If <strong>Merchant</strong> does not provide the consent to the change in Fees, then <strong>Merchant</strong> must immediately close <strong>Merchant</strong>’s Account.</p>
                    <p className="text !text-[16px] mb-2">9.3. <strong>Merchant</strong> agrees that <strong>Siquro</strong> will make settlement transaction on a weekly basis (or otherwise agreed) transferring the funds to the settlement account specified by <strong>Merchant</strong> in Payment Processing Services Contract.</p>
                    <p className="text !text-[16px] mb-2">9.4. Where payments received through <strong>Merchant</strong>’s website are held by <strong>Siquro</strong>, <strong>Merchant</strong> agrees that it will assume the volatility risks of the local currency that have chosen to receive payment in from <strong>Siquro</strong>, between the time that <strong>Siquro</strong> receives the payment from the <strong>Merchant</strong> Customer and the time that <strong>Siquro</strong> transfers the payment to <strong>Merchant</strong>’s bank account in accordance with the Payment Processing Services Contract.</p>
                    <ol className="py-5 title-h4">
                        <li>RETURNS AND REFUNDS</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">10.1. <strong>Merchant</strong> agrees to process returns of, and provide refunds and adjustments for the goods or services rendered through its website and <strong>Merchant</strong> Account in accordance with this Agreement, Payment Processing Services Contract and Card Organization rules.</p>
                    <ol className="py-5 title-h4">
                        <li>CHARGEBACKS</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">11.1. Chargebacks can be received for a number of reasons, including, but not limited to, any one of the following: </p>
                    <p className="text !text-[16px] mb-2">(i) A refund is not issued to a customer upon the return or non-delivery of goods or services;</p>
                    <p className="text !text-[16px] mb-2">(ii) An authorization/approval code was required and not obtained;</p>
                    <p className="text !text-[16px] mb-2">(iii) The transaction was allegedly  fraudulent; </p>
                    <p>(iv) The  customer  disputes  the  Card  sale  or  the  signature  on  the  sale documentation,  or  claims  that  the  sale  is  subject  to  a  set-off, defense or counterclaim; or</p>
                    <p className="text !text-[16px] mb-2">(v) The customer refuses to make payment for a Card sale because in the customer’s good faith opinion, a claim or complaint has not been resolved, or has been resolved but in an unsatisfactory manner. </p>
                    <p className="text !text-[16px] mb-2">11.2. For any transaction that results in a Chargeback, <strong>Siquro</strong> may withhold the Chargeback amount from the <strong>Merchant</strong>’s Rolling Reserve or <strong>Merchant</strong> Account. <strong>Merchant</strong> may be subject to a chargeback on sales for a minimum period of 180 days from the date the sale was processed. Siquro may deduct the amount of any Chargeback and any associated fees, fines, or penalties assessed by <strong>Siquro</strong> from <strong>Merchant</strong> Account, its Rolling Reserve, if any, any proceeds due to <strong>Merchant</strong>, or its bank account.</p>
                    <ol className="py-5 title-h4">
                        <li>TAXES</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">12.1. It is the <strong>Merchant</strong>’s sole responsibility to determine which, if any, taxes apply to the payments received, and to report and remit the  correct  tax  to  the  appropriate  tax  authority. <strong>Siquro</strong> is  not  obligated   to   determine   whether   taxes   apply,   and   is not responsible to  collect,  report,  or  remit  any  taxes  arising  from any Transaction.</p>
                    <ol className="py-5 title-h4">
                        <li>RESTRICTED ACTIVITIES ON THE MERCHANT ACCOUNT</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">13.1. <strong>Siquro</strong> does not accept and process payments from or to sanctioned countries and territories in accordance with Canadian laws and regulations, as well as other binding international legal standards.</p>
                    <p className="text !text-[16px] mb-2">13.2. <strong>Siquro</strong> does not provide services to <strong>Merchant</strong>s, who are engaged in restricted activities. <strong>Siquro</strong> has listed a number of activities that are restricted or prohibited as they relate to the use of the <strong>Siquro</strong> Services, the terms of this agreement, the applicable laws, regulations, directives and decrees that may be issued from time to time by the <strong>Siquro</strong>, the jurisdiction it is authorized, the jurisdictions of its cross border activities and Canada. The <strong>Merchant</strong> agrees that engaging in any of the below activities, may cause the <strong>Siquro</strong> service quality to suffer, and that <strong>Merchant</strong> may restrict the level of safe access that <strong>Merchant</strong> may enjoy. Such activities include:</p>
                    <p className="text !text-[16px] mb-2">9.5.1. Violating any law, regulation, directive, statute or contract in relation the Service received, including without limitation, money laundering laws and regulations, consumer and personal data protection, the payment services regulations and its directives;</p>
                    <p className="text !text-[16px] mb-2">9.5.2. Violating the terms and conditions, including without limitation any other policies and/or regulations related to Services;</p>
                    <p className="text !text-[16px] mb-2">9.5.3. Acting in a manner that is offensive, harassing or demeaning to other <strong>Merchants</strong>, to <strong>Siquro</strong> and/or its partners and third parties;</p>
                    <p className="text !text-[16px] mb-2">9.5.4. Providing inaccurate, disingenuous, misleading or entirely false (deliberately) information without justifiable cause;</p>
                    <p className="text !text-[16px] mb-2">9.5.5. Sending and receiving what may be deemed as unauthorized funds or funds from fraudulent transactions;</p>
                    <p className="text !text-[16px] mb-2">9.5.6. Infringement of <strong>Siquro</strong> copyrights, patent, trademarks or any other intellectual property rights;</p>
                    <p className="text !text-[16px] mb-2">9.5.7. Not being cooperative with <strong>Siquro</strong> when requested to provide additional information that will allow <strong>Siquro</strong> to better familiarize itself with the nature of <strong>Merchant</strong>’s business and continuing operations;</p>
                    <p className="text !text-[16px] mb-2">9.5.8. Refusing to provide confirmation of <strong>Merchant’s</strong> identity and verification of details when requested upon, in order for <strong>Siquro</strong> to perform an investigation when needed;</p>
                    <p className="text !text-[16px] mb-2">9.5.9. Sending or submitting to <strong>Siquro</strong> documents that <strong>Siquro</strong> reasonably believes to be fraudulent;</p>
                    <p className="text !text-[16px] mb-2">9.5.10. Using tools and mechanisms to hide <strong>Merchant</strong>’s identity and location (use of proxy and other anonymizing technics);</p>
                    <p className="text !text-[16px] mb-2">9.5.11. Causing and maintaining an account with a balance owed to <strong>Siquro</strong> (negative balance);</p>
                    <p className="text !text-[16px] mb-2">9.5.12. Engaging in activities that may cause <strong>Siquro</strong> with increased risk of fraud or credit exposure that is beyond the acceptable limits set by <strong>Siquro</strong>;</p>
                    <p className="text !text-[16px] mb-2">9.5.13. Engaging in activities that lead to <strong>Siquro</strong> handling a disproportionate number of claims settled in favor of the claimant <strong>Merchant</strong>;</p>
                    <p className="text !text-[16px] mb-2">9.5.14. Using the <strong>Siquro</strong> Services from a jurisdiction that the <strong>Siquro</strong> authorization does not cover;</p>
                    <p className="text !text-[16px] mb-2">9.5.15. Intentionally or unintentionally facilitate any malicious computer programming routines that may cause damage, harmfully interfere with, clandestinely capture or steal any system, data or information;</p>
                    <p className="text !text-[16px] mb-2">9.5.16. Facilitating any viruses, Trojan horses, worms or other computer programming tools, as well as using of anonymizing proxy, that may make damage to <strong>Siquro</strong> system;</p>
                    <p className="text !text-[16px] mb-2">9.5.17. Intentionally or unintentionally using any automatic device process, or manual process to monitor or copy <strong>Siquro</strong> website and/or mobile application without the <strong>Siquro</strong> prior written consent;</p>
                    <p className="text !text-[16px] mb-2">9.5.18. <strong>Merchant</strong>’s actions may present <strong>Siquro</strong> internet service providers, partners or other suppliers to seize offering their services to <strong>Siquro</strong>;</p>
                    <p className="text !text-[16px] mb-2">9.5.19. Acting in a manner that has a negative interference with the provision of the <strong>Siquro</strong> service in accordance with the terms of this Agreement;</p>
                    <p className="text !text-[16px] mb-2">9.5.20. Using the Services in a manner that could cause a risk of non-compliance with the <strong>Siquro</strong> anti-money laundering, counter terrorist financing and other relevant regulatory obligations;</p>
                    <p className="text !text-[16px] mb-2">9.5.21. Using the <strong>Siquro</strong> Services in a manner that may result in complaints, disputes, claims, reversals, chargebacks, fees, fines, penalties and other liability to <strong>Siquro</strong>, a <strong>Merchant</strong>, or a third party;</p>
                    <p className="text !text-[16px] mb-2">9.5.22. Disclosing information of other <strong>Merchant</strong>’s to third parties;</p>
                    <p className="text !text-[16px] mb-2">9.5.23. Using the Service in a manner that deviates from what is prescribed in this Terms and Conditions.</p>
                    <ol className="py-5 title-h4">
                        <li>UNAUTHORIZED TRANSACTIONS</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">14.1. <strong>Siquro</strong> shall make every effort to avoid unauthorized transactions to take place on the <strong>Merchant</strong>’s Account. For these reasons every <strong>Merchant</strong> shall be fully identified by presenting all the necessary information and/or documentation.</p>
                    <p className="text !text-[16px] mb-2">14.2. In the events, if the <strong>Merchant</strong> reasonably believes that his Account has been compromised, hacked, misused by third parties in any way or had been otherwise used in an unauthorized way the <strong>Merchant</strong> duly agrees to notify <strong>Siquro</strong> immediately by using any available communication channel. In such a case the <strong>Merchant</strong> duly impliedly authorizes <strong>Siquro</strong> to block any Transactions on the Account immediately. For further communication further identification verification may be carried out by <strong>Siquro</strong>.</p>
                    <p className="text !text-[16px] mb-2">14.3. <strong>Siquro</strong> reserves a right to block the <strong>Merchant</strong>’s account in case it reasonably believes that the <strong>Merchant</strong>’s Account has been compromised, hacked, misused by third parties in any way or had been otherwise used in an unauthorised way. <strong>Siquro</strong> shall notify the <strong>Merchant</strong> in event of blocking as soon as it might be reasonably necessary in the situation.</p>
                    <p className="text !text-[16px] mb-2">14.4. <strong>Siquro</strong> shall not bear any responsibility for any losses resulting from unauthorised use of the Account or Services, including to any Transactions made in the <strong>Siquro</strong> System or outside it.</p>
                    <ol className="py-5 title-h4">
                        <li>AMENDMENTS OF CONDITIONS</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">15.1. <strong>Siquro</strong> shall be entitled to amend these Conditions at any time without giving a prior notice. It is <strong>Merchant</strong>’s responsibility to track the changes are available.</p>
                    <p className="text !text-[16px] mb-2">15.2. <strong>Siquro</strong> expressly reserves the right to use its website to inform the <strong>Merchant</strong> about any changes in these Conditions and the posting of a notice on <strong>Siquro</strong> website shall be deemed a valid notification of such changes to the <strong>Merchant</strong>. The <strong>Merchant</strong> undertakes to regularly review <strong>Siquro</strong> website and/or to regularly access his online reporting where relevant information may be published.</p>
                    <p className="text !text-[16px] mb-2">15.3. Also immediate will be any amendments necessary due to the enrichment of the Service and its delivery or in cases where <strong>Merchant</strong>’s rights and obligations are not adversely affected. <strong>Siquro</strong> will not provide the <strong>Merchant</strong> with any notice of such immediate changes.</p>
                    <ol className="py-5 title-h4">
                        <li>SUSPENSION AND TERMINATION OF THE RELATIONSHIPS</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">16.1. The Business relationships between the <strong>Merchant</strong> and <strong>Siquro</strong> shall remain in force until terminated by mutual agreement between the <strong>Merchant</strong> and <strong>Siquro</strong>.</p>
                    <p className="text !text-[16px] mb-2">16.2. Without prejudice of the right of early termination as set forth in the next Paragraph, either party is entitled to terminate its relationship with the other at any time, without reason, by giving no less than one (1) week prior written notice, including but not limited to notice given by e-mail to the other party, such notice to specify the date on which the termination is to become effective. No penalty shall be payable by either party upon termination of its relationship with the other. Termination shall in no way affect any rights and obligations accrued hereunder until the date of termination. Indeed, the <strong>Merchant</strong> cannot cancel already executed transactions and shall fully remunerate services already provided.</p>
                    <p className="text !text-[16px] mb-2">16.3. The termination of the relationship with the <strong>Merchant</strong> shall extinguish the <strong>Merchant</strong>’s right to use the <strong>Siquro</strong> System as well as all and any software and solutions made available to him by <strong>Siquro</strong>.</p>
                    <p className="text !text-[16px] mb-2">16.4. Upon termination of the relationship, <strong>Siquro</strong> and the <strong>Merchant</strong> undertake to complete all Transactions that are already in progress and the terms of these Conditions shall continue to bind both parties in relation to such transactions. However, <strong>Siquro</strong> shall be entitled to complete all outstanding Transactions of the <strong>Merchant</strong> and to offset, after conversion into the Base Currency, any amount due to the <strong>Merchant</strong> against any amount owed by him, irrespective of the maturation date of any respective Transaction. <strong>Siquro</strong> shall be entitled to deduct all amounts due to it before transferring any funds on any Account of the <strong>Merchant</strong>.</p>
                    <p className="text !text-[16px] mb-2">16.5. Upon termination of the Business relationships with the <strong>Merchant</strong>, the right of the <strong>Merchant</strong> to use any and all of <strong>Siquro</strong> software and systems that have been made available to the <strong>Merchant</strong> during the terms of these Conditions shall expire.</p>
                    <p className="text !text-[16px] mb-2">16.6. <strong>Suspension of relationships by error/without intention to terminate the business relation</strong></p>
                    <p className="text !text-[16px] mb-2">16.6.1. <strong>Siquro</strong> shall have the right at its sole discretion to suspend its relationship with the <strong>Merchant</strong> for a reasonable period of time by notice with immediate effect, upon or at any time after the occurrence of any of the following events:</p>
                    <p className="text !text-[16px] mb-2">16.6.2. If an <strong>Merchant</strong> Account has been switched to the “Closed” mode in the system due to a mistake, meaning without any <strong>Merchant</strong> instruction and out of any applicable internal regulation/terms and conditions, the account may be freely reactivated. In such case, the <strong>Merchant</strong> Account relation is reputed to have been uninterrupted.</p>
                    <p className="text !text-[16px] mb-2">16.6.3. In case the <strong>Merchant</strong> states that the <strong>Merchant</strong> Account closure instruction was given by mistake (for instance by misfiling a withdrawal form), the <strong>Siquro</strong> shall assess, based on the circumstances and explanations given by the <strong>Merchant</strong>, whether it can reasonably be considered that the <strong>Merchant</strong> instruction was mistaken and that the <strong>Merchant</strong> did not want to close the <strong>Merchant</strong> Account. In case the conclusion is that the <strong>Merchant</strong>’s closure instruction was erroneous, the <strong>Merchant</strong> Account relation shall be maintained open/reactivated and is reputed to have been uninterrupted.</p>
                    <p className="text !text-[16px] mb-2">16.7. <strong>Early Termination of the relationships</strong></p>
                    <p className="text !text-[16px] mb-2">16.7.1. <strong>Siquro</strong> shall have the right at its sole discretion to terminate its relationship with the <strong>Merchant</strong> by notice with immediate effect, upon or at any time after the occurrence of any of the following events:</p>
                    <p className="text !text-[16px] mb-2">16.7.1.1. the <strong>Merchant</strong> fails to make any payment or fails to comply fully with any obligations under these Conditions or any transaction;</p>
                    <p className="text !text-[16px] mb-2">16.7.1.2. in case of inability of <strong>Siquro</strong> to identify the Account holder and the beneficial owner of the Account in accordance with anti-money laundering and terrorism financing laws and regulations;</p>
                    <p className="text !text-[16px] mb-2">16.7.1.3. if <strong>Siquro</strong> does not receive upon its request the documents and/or information to satisfy requirements of the anti-money laundering and terrorism financing laws and regulations;</p>
                    <p className="text !text-[16px] mb-2">16.7.1.4. if <strong>Siquro</strong> has reasonable suspicion of fraudulent or criminal activity concerning the use of the <strong>Merchant</strong> Account;</p>
                    <p className="text !text-[16px] mb-2">16.7.1.5. if the <strong>Merchant</strong> dies or loses legal capacity;</p>
                    <p className="text !text-[16px] mb-2">16.7.1.6. if the <strong>Merchant</strong> enters into liquidation or into an insolvency arrangement (including an arrangement with its creditors), or if a receiver is appointed over all or part of its assets or undertaking;</p>
                    <p className="text !text-[16px] mb-2">16.7.1.7. if any of the representations or warranties given by the <strong>Merchant</strong> are, or become, untrue;</p>
                    <p className="text !text-[16px] mb-2">16.7.1.8. if <strong>Siquro</strong> reasonably considers it necessary for its own protection or the protection of its associates;</p>
                    <p className="text !text-[16px] mb-2">16.7.1.9. if <strong>Siquro</strong> is given a direction to do so by any regulator or other competent regulatory, tax or other authority.</p>
                    <p className="text !text-[16px] mb-2">16.8. The <strong>Merchant</strong> acknowledges, recognizes and agrees that <strong>Siquro</strong> shall not be liable for any consequences of it taking the steps described in this Paragraph. The rights described in this Paragraph shall be in addition to any other rights which <strong>Siquro</strong> may have against the <strong>Merchant</strong> under these Conditions or under applicable law.</p>
                    <p>16.9. If <strong>Siquro</strong> terminates its relationship with a <strong>Merchant</strong>: (i) the funds of <strong>Merchant</strong>’s Account will be transferred to the most recent details <strong>Merchant</strong> has given the bank account in <strong>Merchant</strong>’s name after deducting any charges due and payable by <strong>Merchant</strong>; and (ii) any of <strong>Merchant</strong>’s or <strong>Siquro</strong> rights or liabilities which have accrued prior to the termination shall continue until fully discharged by the relevant party, save for any rights or liabilities, which are expressed to continue after these Conditions end.</p>
                    <ol className="py-5 title-h4">
                        <li>CONFIDENTIALITY</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">17.1. Neither party shall disclose to any person (unless required to do so by any applicable law or by any regulatory or supervisory authority or by any other person entitled by law to require such disclosure) any information relating to the business, transactions, finances or other matters of confidential nature of the other party which it may in the course of its duties or otherwise become aware, and each party shall use all reasonable endeavors to prevent any such disclosure.</p>
                    <p className="text !text-[16px] mb-2">17.2. By adhering to these Conditions, the <strong>Merchant</strong> authorizes <strong>Siquro</strong> to disclose such information relating to the <strong>Merchant</strong> as may be required by any law, rule or regulatory authority without prior notice to the <strong>Merchant</strong>.</p>
                    <ol >
                        <li><strong> WAIVER OF RIGHTS</strong></li>
                    </ol>
                    <p className="text !text-[16px] mb-2">18.1. The rights and remedies contained in these Conditions shall be cumulative and not exclusive of any rights or remedies provided by law. No delay or omission of <strong>Siquro</strong> in exercising any right, power or remedy provided by law or under these Conditions, or partial or defective exercise thereof, shall:</p>
                    <p className="text !text-[16px] mb-2">18.1.1. impair or prevent any further or other exercise of such right, power or remedy; or</p>
                    <p className="text !text-[16px] mb-2">18.1.2. operate as a waiver of such right, power or remedy;</p>
                    <p className="text !text-[16px] mb-2">18.1.3. No waiver of breach of all or part of these Conditions shall (unless expressly agreed in writing by the waiving party) be construed as a waiver of any future breach of the same or as authorizing a continuation of a particular breach.</p>
                    <ol className="py-5 title-h4">
                        <li>REMEDIES</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">19.1. The <strong>Merchant</strong> shall indemnify <strong>Siquro</strong> and keep <strong>Siquro</strong> indemnified against all losses, taxes, expenses, costs and liabilities whatsoever (present, future, contingent or otherwise, and including reasonable legal fees) which may be suffered or incurred by <strong>Siquro</strong> as a result of or in connection with:</p>
                    <p className="text !text-[16px] mb-2">19.1.1. Any breach of these Conditions or Payment Processing Services Contract by the <strong>Merchant</strong>;</p>
                    <p className="text !text-[16px] mb-2">19.1.2. As a result of illegal actions performed by the <strong>Merchant</strong> using <strong>Siquro</strong> services.</p>
                    <ol className="py-5 title-h4">
                        <li>NO LIABILITY FOR TAX</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">20.1. Notwithstanding it is required by the relevant laws <strong>Siquro</strong> has no obligation whatsoever to any taxation or similar authority in respect of any taxation or other similar duty or levy payable by any account holder. It is <strong>Merchant</strong>’s obligation to pay all taxation, duties and levies that are payable by it in respect of <strong>Merchant</strong>’s Account and the Services <strong>Merchant</strong> instructs <strong>Siquro</strong> to carry out.</p>
                    <ol className="py-5 title-h4">
                        <li>FORCE MAJEURE</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">21.1. <strong>Siquro</strong> is not responsible for any breach of these Terms by it, or for any loss <strong>Merchant</strong> incurs in connection with such breach, due to any Force Majeure circumstances.</p>
                    <p className="text !text-[16px] mb-2">21.2. The performance of the <strong>Siquro</strong> Services is deemed to be suspended for the period that the Force Majeure circumstances continue, and <strong>Siquro</strong> will have an extension of time for performance for the duration of that period.</p>
                    <p className="text !text-[16px] mb-2">21.3. If any Force Majeure circumstances occur, <strong>Siquro</strong> may take any action it considers appropriate in connection with the Services and use reasonable endeavors to end the Force Majeure.</p>
                    <p className="text !text-[16px] mb-2">21.4. The condition beyond its reasonable control (Force Majeure) includes but is not limited to governmental action, the war, riots, hurricane, typhoon, acts of terrorism, earthquake, fire, flood, lightning, explosion strikes, lockouts, emergency state, pandemic or any other diseases as defined by the World Health Organization (WHO), prolonged shortage of energy supplies, and acts of state or governmental action prohibiting or impeding any party from performing its respective obligations under the Agreement or other acts of God, labor conditions, power failures, and Internet disturbances.</p>
                    <ol className="py-5 title-h4">
                        <li>COMPLAINTS PROCEDURE</li>
                    </ol>
                    <p>22.1. If the <strong>Merchant</strong> has a complaint regarding the Services or any other matter contained in these Agreement, the <strong>Merchant</strong> can contact <strong>Siquro</strong> through any available communication channel.</p>
                    <ol className="py-5 title-h4">
                        <li>DISPUTE RESOLUTION</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">23.1. The <strong>Merchant</strong> and <strong>Siquro</strong> shall make every endeavor to amicably resolve any dispute, in good faith and in a constructive manner. The <strong>Merchant</strong> acknowledges and agrees that threats and blackmailing towards <strong>Siquro</strong> are prohibited and constitute valid ground for interrupting negotiations and for immediate termination of any Business relationships.</p>
                    <ol className="py-5 title-h4">
                        <li>APPLICABLE LAW AND JURISDICTION</li>
                    </ol>
                    <p className="text !text-[16px] mb-2">24.1. These Conditions are construed in accordance with and shall be governed by the laws of Canada.</p>
                    <p className="text !text-[16px] mb-2">24.2. Any dispute, controversy or claim arising out of or in relation to these Conditions, including the validity, invalidity, breach or termination thereof, shall be settled before the courts of Canada and in accordance with Canadian law.</p>
                    <p className="text !text-[16px] mb-2">24.3. In the event of any conflict between the provisions of this agreement and a Payment Processing Services Contract, the provisions of Payment Processing Services Contract shall prevail, unless the relevant clause expressly provides that it shall prevail, thereby referencing the clause of this agreement over which the applicable schedule is intended to prevail.</p>
            </div>
        </main>
    )
}
export default Terms;